In [1]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [3]:
# define input sequence
parser = (lambda x:datetime.datetime.strptime(x, '%Y.%m.%d')) 
df = pd.read_csv('sp_beaches_update.csv', parse_dates=['Date'])
df = df.sort_values(by=['Date'])
df=df.loc[~df['Enterococcus'].isnull()]
#remover a praia do Leste, da cidade de iguape, pois esta praia sumiu por erosão em 2012
#remover a Lagoa Prumirim, da cidade de Ubatuba, pois esta praia possui somente 3 medições
df = df.loc[df['Beach']!='DO LESTE'].loc[df['Beach']!='LAGOA PRUMIRIM']
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69325 entries, 0 to 66738
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          69325 non-null  object
 1   Beach         69325 non-null  object
 2   Date          69325 non-null  datetime64[ns]
 3   Enterococcus  69325 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 2.6+ MB

In [4]:
df.loc[df['City']=='UBATUBA'].loc[df['Beach']=='GRANDE']

          City   Beach       Date  Enterococcus
7614   UBATUBA  GRANDE 2012-01-03             5
7615   UBATUBA  GRANDE 2012-01-08            42
7616   UBATUBA  GRANDE 2012-01-15            92
7617   UBATUBA  GRANDE 2012-01-22            16
7618   UBATUBA  GRANDE 2012-01-29             9
...        ...     ...        ...           ...
69094  UBATUBA  GRANDE 2020-10-05            31
69095  UBATUBA  GRANDE 2020-10-12            15
69096  UBATUBA  GRANDE 2020-10-19             3
69097  UBATUBA  GRANDE 2020-10-26            12
69098  UBATUBA  GRANDE 2020-11-02            13

[434 rows x 4 columns]

In [7]:
# selecionar praias com medições semanal
df_freq = pd.read_csv('frequencia_praias.csv')
df_freq = df_freq.loc[df_freq['Beach']!='DO LESTE'].loc[df['Beach']!='LAGOA PRUMIRIM']
df_freq = df_freq.loc[df_freq['Frequency']=='SEMANAL']
df_freq

         City                          Beach Frequency
9    BERTIOGA        BORACÉIA - COL. MARISTA   SEMANAL
10   BERTIOGA                 BORACÉIA - SUL   SEMANAL
11   BERTIOGA                      GUARATUBA   SEMANAL
12   BERTIOGA  SÃO LOURENÇO (JUNTO AO MORRO)   SEMANAL
13   BERTIOGA           SÃO LOURENÇO (RUA 2)   SEMANAL
..        ...                            ...       ...
169   UBATUBA                           DURA   SEMANAL
170   UBATUBA    LAGOINHA (R. ENGENHO VELHO)   SEMANAL
171   UBATUBA             LAGOINHA (CAMPING)   SEMANAL
172   UBATUBA                           SAPÉ   SEMANAL
173   UBATUBA                      MARANDUBA   SEMANAL

[165 rows x 3 columns]

In [9]:
n_steps = 16
for cidade in df_freq.City.unique():
    #print(df2.loc[df2['City']==cidade].Beach.unique())
    for praia in df_freq.loc[df_freq['City']==cidade].Beach.unique():
        print(f'iniciando: {cidade} - {praia}')
        df_beach = df.loc[df['City']==cidade].loc[df['Beach']==praia][['Date','Enterococcus']]
        df_beach.columns = ['ds', 'y']
        df_beach.set_index('ds', inplace=True)
        X, y = split_sequence(df_beach.values, n_steps)
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))
        model = Sequential()
        model.add(LSTM(104, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
        model.add(LSTM(104, activation='relu'))
        model.add(Dense(1))
        model.compile(optimizer='adam', loss='mse')
        print('Treinando modelo: '+cidade+'-'+praia)
        
        with tf.device('/GPU:0'): 
            R = model.fit(X, y, epochs=200, verbose=0)
        loss=round(R.history['loss'][-1])
        model.save('model'+cidade+'-'+praia+'.h5')        
        print('Modelo Treinado: '+cidade+'-'+praia+'- MSE:'+str(loss))

iniciando: BERTIOGA - BORACÉIA - COL. MARISTA
Treinando modelo: BERTIOGA-BORACÉIA - COL. MARISTA
Modelo Treinado: BERTIOGA-BORACÉIA - COL. MARISTA- MSE:646
iniciando: BERTIOGA - BORACÉIA - SUL
Treinando modelo: BERTIOGA-BORACÉIA - SUL
Modelo Treinado: BERTIOGA-BORACÉIA - SUL- MSE:1666
iniciando: BERTIOGA - GUARATUBA
Treinando modelo: BERTIOGA-GUARATUBA
Modelo Treinado: BERTIOGA-GUARATUBA- MSE:791
iniciando: BERTIOGA - SÃO LOURENÇO (JUNTO AO MORRO)
Treinando modelo: BERTIOGA-SÃO LOURENÇO (JUNTO AO MORRO)
Modelo Treinado: BERTIOGA-SÃO LOURENÇO (JUNTO AO MORRO)- MSE:964
iniciando: BERTIOGA - SÃO LOURENÇO (RUA 2)
Treinando modelo: BERTIOGA-SÃO LOURENÇO (RUA 2)
Modelo Treinado: BERTIOGA-SÃO LOURENÇO (RUA 2)- MSE:1399
iniciando: BERTIOGA - ENSEADA - INDAIÁ
Treinando modelo: BERTIOGA-ENSEADA - INDAIÁ
Modelo Treinado: BERTIOGA-ENSEADA - INDAIÁ- MSE:2416
iniciando: BERTIOGA - ENSEADA - VISTA LINDA
Treinando modelo: BERTIOGA-ENSEADA - VISTA LINDA
Modelo Treinado: BERTIOGA-ENSEADA - VISTA LINDA- MSE:2725
iniciando: BERTIOGA - ENSEADA - COLÔNIA DO SESC
Treinando modelo: BERTIOGA-ENSEADA - COLÔNIA DO SESC
Modelo Treinado: BERTIOGA-ENSEADA - COLÔNIA DO SESC- MSE:4043
iniciando: BERTIOGA - ENSEADA - R. RAFAEL COSTABILI
Treinando modelo: BERTIOGA-ENSEADA - R. RAFAEL COSTABILI
Modelo Treinado: BERTIOGA-ENSEADA - R. RAFAEL COSTABILI- MSE:4367
iniciando: CARAGUATATUBA - TABATINGA (250M RIO TABATINGA)
Treinando modelo: CARAGUATATUBA-TABATINGA (250M RIO TABATINGA)
Modelo Treinado: CARAGUATATUBA-TABATINGA (250M RIO TABATINGA)- MSE:8361
iniciando: CARAGUATATUBA - TABATINGA (CONDOM. GAIVOTAS)
Treinando modelo: CARAGUATATUBA-TABATINGA (CONDOM. GAIVOTAS)
Modelo Treinado: CARAGUATATUBA-TABATINGA (CONDOM. GAIVOTAS)- MSE:0
iniciando: CARAGUATATUBA - MOCOÓCA
Treinando modelo: CARAGUATATUBA-MOCOÓCA
Modelo Treinado: CARAGUATATUBA-MOCOÓCA- MSE:1027
iniciando: CARAGUATATUBA - COCANHA
Treinando modelo: CARAGUATATUBA-COCANHA
Modelo Treinado: CARAGUATATUBA-COCANHA- MSE:3961
iniciando: CARAGUATATUBA - MASSAGUAÇU (R. MARIA CARLOTA)
Treinando modelo: CARAGUATATUBA-MASSAGUAÇU (R. MARIA CARLOTA)
Modelo Treinado: CARAGUATATUBA-MASSAGUAÇU (R. MARIA CARLOTA)- MSE:2
iniciando: CARAGUATATUBA - MASSAGUAÇU (AV. M. H. CARVALHO)
Treinando modelo: CARAGUATATUBA-MASSAGUAÇU (AV. M. H. CARVALHO)
Modelo Treinado: CARAGUATATUBA-MASSAGUAÇU (AV. M. H. CARVALHO)- MSE:811
iniciando: CARAGUATATUBA - CAPRICÓRNIO
Treinando modelo: CARAGUATATUBA-CAPRICÓRNIO
Modelo Treinado: CARAGUATATUBA-CAPRICÓRNIO- MSE:40
iniciando: CARAGUATATUBA - LAGOA AZUL
Treinando modelo: CARAGUATATUBA-LAGOA AZUL
Modelo Treinado: CARAGUATATUBA-LAGOA AZUL- MSE:6764
iniciando: CARAGUATATUBA - MARTIM DE SÁ
Treinando modelo: CARAGUATATUBA-MARTIM DE SÁ
Modelo Treinado: CARAGUATATUBA-MARTIM DE SÁ- MSE:6452
iniciando: CARAGUATATUBA - PRAINHA
Treinando modelo: CARAGUATATUBA-PRAINHA
Modelo Treinado: CARAGUATATUBA-PRAINHA- MSE:6684
iniciando: CARAGUATATUBA - CENTRO
Treinando modelo: CARAGUATATUBA-CENTRO
Modelo Treinado: CARAGUATATUBA-CENTRO- MSE:24913
iniciando: CARAGUATATUBA - INDAIÁ
Treinando modelo: CARAGUATATUBA-INDAIÁ
Modelo Treinado: CARAGUATATUBA-INDAIÁ- MSE:26338
iniciando: CARAGUATATUBA - PAN BRASIL
Treinando modelo: CARAGUATATUBA-PAN BRASIL
Modelo Treinado: CARAGUATATUBA-PAN BRASIL- MSE:7085
iniciando: CARAGUATATUBA - PALMEIRAS
Treinando modelo: CARAGUATATUBA-PALMEIRAS
Modelo Treinado: CARAGUATATUBA-PALMEIRAS- MSE:13263
iniciando: CARAGUATATUBA - PORTO NOVO
Treinando modelo: CARAGUATATUBA-PORTO NOVO
Modelo Treinado: CARAGUATATUBA-PORTO NOVO- MSE:20255
iniciando: CUBATÃO - RIO PEREQUÊ
Treinando modelo: CUBATÃO-RIO PEREQUÊ
Modelo Treinado: CUBATÃO-RIO PEREQUÊ- MSE:1245
iniciando: GUARUJÁ - PEREQUÊ
Treinando modelo: GUARUJÁ-PEREQUÊ
Modelo Treinado: GUARUJÁ-PEREQUÊ- MSE:354111
iniciando: GUARUJÁ - PERNAMBUCO
Treinando modelo: GUARUJÁ-PERNAMBUCO
Modelo Treinado: GUARUJÁ-PERNAMBUCO- MSE:5507
iniciando: GUARUJÁ - ENSEADA (ESTR. DE PERNAMBUCO)
Treinando modelo: GUARUJÁ-ENSEADA (ESTR. DE PERNAMBUCO)
Modelo Treinado: GUARUJÁ-ENSEADA (ESTR. DE PERNAMBUCO)- MSE:11593
iniciando: GUARUJÁ - ENSEADA (AV. ATLÂNTICA)
Treinando modelo: GUARUJÁ-ENSEADA (AV. ATLÂNTICA)
Modelo Treinado: GUARUJÁ-ENSEADA (AV. ATLÂNTICA)- MSE:5234
iniciando: GUARUJÁ - ENSEADA (R. CHILE)
Treinando modelo: GUARUJÁ-ENSEADA (R. CHILE)
Modelo Treinado: GUARUJÁ-ENSEADA (R. CHILE)- MSE:5970
iniciando: GUARUJÁ - ENSEADA (AV. SANTA MARIA)
Treinando modelo: GUARUJÁ-ENSEADA (AV. SANTA MARIA)
Modelo Treinado: GUARUJÁ-ENSEADA (AV. SANTA MARIA)- MSE:9620
iniciando: GUARUJÁ - PITANGUEIRAS (AV. PUGLISI)
Treinando modelo: GUARUJÁ-PITANGUEIRAS (AV. PUGLISI)
Modelo Treinado: GUARUJÁ-PITANGUEIRAS (AV. PUGLISI)- MSE:2604
iniciando: GUARUJÁ - PITANGUEIRAS (R. SILVIA VALADÃO)
Treinando modelo: GUARUJÁ-PITANGUEIRAS (R. SILVIA VALADÃO)
Modelo Treinado: GUARUJÁ-PITANGUEIRAS (R. SILVIA VALADÃO)- MSE:6783
iniciando: GUARUJÁ - ASTÚRIAS
Treinando modelo: GUARUJÁ-ASTÚRIAS
Modelo Treinado: GUARUJÁ-ASTÚRIAS- MSE:4418
iniciando: GUARUJÁ - TOMBO
Treinando modelo: GUARUJÁ-TOMBO
Modelo Treinado: GUARUJÁ-TOMBO- MSE:777
iniciando: GUARUJÁ - GUAIÚBA
Treinando modelo: GUARUJÁ-GUAIÚBA
Modelo Treinado: GUARUJÁ-GUAIÚBA- MSE:3805
iniciando: ILHA ANCHIETA - PRAIA DAS PALMAS
Treinando modelo: ILHA ANCHIETA-PRAIA DAS PALMAS
Modelo Treinado: ILHA ANCHIETA-PRAIA DAS PALMAS- MSE:1
iniciando: ILHA ANCHIETA - PRAIA DO SAPATEIRO
Treinando modelo: ILHA ANCHIETA-PRAIA DO SAPATEIRO
Modelo Treinado: ILHA ANCHIETA-PRAIA DO SAPATEIRO- MSE:0
iniciando: ILHA ANCHIETA - PRAIA DO PRESIDIO
Treinando modelo: ILHA ANCHIETA-PRAIA DO PRESIDIO
Modelo Treinado: ILHA ANCHIETA-PRAIA DO PRESIDIO- MSE:6
iniciando: ILHA ANCHIETA - PRAIA DO ENGENHO
Treinando modelo: ILHA ANCHIETA-PRAIA DO ENGENHO
Modelo Treinado: ILHA ANCHIETA-PRAIA DO ENGENHO- MSE:95
iniciando: ILHA ANCHIETA - PRAIA DE FORA
Treinando modelo: ILHA ANCHIETA-PRAIA DE FORA
Modelo Treinado: ILHA ANCHIETA-PRAIA DE FORA- MSE:569
iniciando: ILHA ANCHIETA - PRAIA DO SUL
Treinando modelo: ILHA ANCHIETA-PRAIA DO SUL
Modelo Treinado: ILHA ANCHIETA-PRAIA DO SUL- MSE:28
iniciando: ILHA ANCHIETA - PRAINHA DO LESTE
Treinando modelo: ILHA ANCHIETA-PRAINHA DO LESTE
Modelo Treinado: ILHA ANCHIETA-PRAINHA DO LESTE- MSE:132
iniciando: ILHABELA - ARMAÇÃO
Treinando modelo: ILHABELA-ARMAÇÃO
Modelo Treinado: ILHABELA-ARMAÇÃO- MSE:15672
iniciando: ILHABELA - PINTO
Treinando modelo: ILHABELA-PINTO
Modelo Treinado: ILHABELA-PINTO- MSE:13622
iniciando: ILHABELA - SINO
Treinando modelo: ILHABELA-SINO
Modelo Treinado: ILHABELA-SINO- MSE:12002
iniciando: ILHABELA - SIRIÚBA
Treinando modelo: ILHABELA-SIRIÚBA
Modelo Treinado: ILHABELA-SIRIÚBA- MSE:14904
iniciando: ILHABELA - VIANA
Treinando modelo: ILHABELA-VIANA
Modelo Treinado: ILHABELA-VIANA- MSE:15961
iniciando: ILHABELA - BARREIROS NORTE
Treinando modelo: ILHABELA-BARREIROS NORTE
Modelo Treinado: ILHABELA-BARREIROS NORTE- MSE:12638
iniciando: ILHABELA - BARREIROS SUL
Treinando modelo: ILHABELA-BARREIROS SUL
Modelo Treinado: ILHABELA-BARREIROS SUL- MSE:8715
iniciando: ILHABELA - SACO DA CAPELA
Treinando modelo: ILHABELA-SACO DA CAPELA
Modelo Treinado: ILHABELA-SACO DA CAPELA- MSE:8326
iniciando: ILHABELA - ENGENHO D'ÁGUA
Treinando modelo: ILHABELA-ENGENHO D'ÁGUA
Modelo Treinado: ILHABELA-ENGENHO D'ÁGUA- MSE:13021
iniciando: ILHABELA - ITAQUANDUBA
Treinando modelo: ILHABELA-ITAQUANDUBA
Modelo Treinado: ILHABELA-ITAQUANDUBA- MSE:70404
iniciando: ILHABELA - ITAGUAÇU
Treinando modelo: ILHABELA-ITAGUAÇU
Modelo Treinado: ILHABELA-ITAGUAÇU- MSE:43139
iniciando: ILHABELA - PEREQUÊ
Treinando modelo: ILHABELA-PEREQUÊ
Modelo Treinado: ILHABELA-PEREQUÊ- MSE:23734
iniciando: ILHABELA - ILHA DAS CABRAS
Treinando modelo: ILHABELA-ILHA DAS CABRAS
Modelo Treinado: ILHABELA-ILHA DAS CABRAS- MSE:11552
iniciando: ILHABELA - PORTINHO
Treinando modelo: ILHABELA-PORTINHO
Modelo Treinado: ILHABELA-PORTINHO- MSE:16400
iniciando: ILHABELA - FEITICEIRA
Treinando modelo: ILHABELA-FEITICEIRA
Modelo Treinado: ILHABELA-FEITICEIRA- MSE:11098
iniciando: ILHABELA - JULIÃO
Treinando modelo: ILHABELA-JULIÃO
Modelo Treinado: ILHABELA-JULIÃO- MSE:8739
iniciando: ILHABELA - GRANDE
Treinando modelo: ILHABELA-GRANDE
Modelo Treinado: ILHABELA-GRANDE- MSE:5020
iniciando: ILHABELA - CURRAL
Treinando modelo: ILHABELA-CURRAL

Modelo Treinado: ILHABELA-CURRAL- MSE:3207
iniciando: ITANHAÉM - CAMPOS ELÍSEOS
Treinando modelo: ITANHAÉM-CAMPOS ELÍSEOS
Modelo Treinado: ITANHAÉM-CAMPOS ELÍSEOS- MSE:11727
iniciando: ITANHAÉM - SUARÃO
Treinando modelo: ITANHAÉM-SUARÃO
Modelo Treinado: ITANHAÉM-SUARÃO- MSE:9508
iniciando: ITANHAÉM - SUARÃO - AFPESP
Treinando modelo: ITANHAÉM-SUARÃO - AFPESP
Modelo Treinado: ITANHAÉM-SUARÃO - AFPESP- MSE:4578
iniciando: ITANHAÉM - PARQUE BALNEÁRIO
Treinando modelo: ITANHAÉM-PARQUE BALNEÁRIO
Modelo Treinado: ITANHAÉM-PARQUE BALNEÁRIO- MSE:10171
iniciando: ITANHAÉM - CENTRO
Treinando modelo: ITANHAÉM-CENTRO
Modelo Treinado: ITANHAÉM-CENTRO- MSE:11902
iniciando: ITANHAÉM - PRAIA DOS PESCADORES
Treinando modelo: ITANHAÉM-PRAIA DOS PESCADORES
Modelo Treinado: ITANHAÉM-PRAIA DOS PESCADORES- MSE:6872
iniciando: ITANHAÉM - SONHO
Treinando modelo: ITANHAÉM-SONHO
Modelo Treinado: ITANHAÉM-SONHO- MSE:6049
iniciando: ITANHAÉM - JARDIM CIBRATEL
Treinando modelo: ITANHAÉM-JARDIM CIBRATEL
Modelo Treinado: ITANHAÉM-JARDIM CIBRATEL- MSE:8691
iniciando: ITANHAÉM - ESTÂNCIA BALNEÁRIA
Treinando modelo: ITANHAÉM-ESTÂNCIA BALNEÁRIA
Modelo Treinado: ITANHAÉM-ESTÂNCIA BALNEÁRIA- MSE:9209
iniciando: ITANHAÉM - JARDIM SÃO FERNANDO
Treinando modelo: ITANHAÉM-JARDIM SÃO FERNANDO
Modelo Treinado: ITANHAÉM-JARDIM SÃO FERNANDO- MSE:7529
iniciando: ITANHAÉM - JARDIM REGINA
Treinando modelo: ITANHAÉM-JARDIM REGINA
Modelo Treinado: ITANHAÉM-JARDIM REGINA- MSE:29582
iniciando: ITANHAÉM - BALNEÁRIO GAIVOTA
Treinando modelo: ITANHAÉM-BALNEÁRIO GAIVOTA
Modelo Treinado: ITANHAÉM-BALNEÁRIO GAIVOTA- MSE:11122
iniciando: MONGAGUÁ - ITAPOÃ - VILA SÃO PAULO
Treinando modelo: MONGAGUÁ-ITAPOÃ - VILA SÃO PAULO
Modelo Treinado: MONGAGUÁ-ITAPOÃ - VILA SÃO PAULO- MSE:2062
iniciando: MONGAGUÁ - CENTRAL
Treinando modelo: MONGAGUÁ-CENTRAL
Modelo Treinado: MONGAGUÁ-CENTRAL- MSE:16178
iniciando: MONGAGUÁ - VERA CRUZ
Treinando modelo: MONGAGUÁ-VERA CRUZ
Modelo Treinado: MONGAGUÁ-VERA CRUZ- MSE:17565
iniciando: MONGAGUÁ - SANTA EUGÊNIA
Treinando modelo: MONGAGUÁ-SANTA EUGÊNIA
Modelo Treinado: MONGAGUÁ-SANTA EUGÊNIA- MSE:17824
iniciando: MONGAGUÁ - ITAÓCA
Treinando modelo: MONGAGUÁ-ITAÓCA
Modelo Treinado: MONGAGUÁ-ITAÓCA- MSE:6773
iniciando: MONGAGUÁ - AGENOR DE CAMPOS
Treinando modelo: MONGAGUÁ-AGENOR DE CAMPOS
Modelo Treinado: MONGAGUÁ-AGENOR DE CAMPOS- MSE:18223
iniciando: MONGAGUÁ - FLÓRIDA MIRIM
Treinando modelo: MONGAGUÁ-FLÓRIDA MIRIM
Modelo Treinado: MONGAGUÁ-FLÓRIDA MIRIM- MSE:12980
iniciando: PERUÍBE - PERUÍBE (R. ICARAÍBA)
Treinando modelo: PERUÍBE-PERUÍBE (R. ICARAÍBA)
Modelo Treinado: PERUÍBE-PERUÍBE (R. ICARAÍBA)- MSE:5670
iniciando: PERUÍBE - PERUÍBE (PARQUE TURÍSTICO)
Treinando modelo: PERUÍBE-PERUÍBE (PARQUE TURÍSTICO)
Modelo Treinado: PERUÍBE-PERUÍBE (PARQUE TURÍSTICO)- MSE:13564
iniciando: PERUÍBE - PERUÍBE (BALN. SÃO JOÃO BATISTA)
Treinando modelo: PERUÍBE-PERUÍBE (BALN. SÃO JOÃO BATISTA)
Modelo Treinado: PERUÍBE-PERUÍBE (BALN. SÃO JOÃO BATISTA)- MSE:15427
iniciando: PERUÍBE - PERUÍBE (AV. S. JOÃO)
Treinando modelo: PERUÍBE-PERUÍBE (AV. S. JOÃO)
Modelo Treinado: PERUÍBE-PERUÍBE (AV. S. JOÃO)- MSE:12425
iniciando: PERUÍBE - PRAINHA
Treinando modelo: PERUÍBE-PRAINHA
Modelo Treinado: PERUÍBE-PRAINHA- MSE:13332
iniciando: PERUÍBE - GUARAÚ
Treinando modelo: PERUÍBE-GUARAÚ
Modelo Treinado: PERUÍBE-GUARAÚ- MSE:9241
iniciando: PRAIA GRANDE - CANTO DO FORTE
Treinando modelo: PRAIA GRANDE-CANTO DO FORTE
Modelo Treinado: PRAIA GRANDE-CANTO DO FORTE- MSE:22706
iniciando: PRAIA GRANDE - BOQUEIRÃO
Treinando modelo: PRAIA GRANDE-BOQUEIRÃO
Modelo Treinado: PRAIA GRANDE-BOQUEIRÃO- MSE:148658
iniciando: PRAIA GRANDE - GUILHERMINA
Treinando modelo: PRAIA GRANDE-GUILHERMINA
Modelo Treinado: PRAIA GRANDE-GUILHERMINA- MSE:28695
iniciando: PRAIA GRANDE - AVIAÇÃO
Treinando modelo: PRAIA GRANDE-AVIAÇÃO
Modelo Treinado: PRAIA GRANDE-AVIAÇÃO- MSE:26794
iniciando: PRAIA GRANDE - VILA TUPI
Treinando modelo: PRAIA GRANDE-VILA TUPI
Modelo Treinado: PRAIA GRANDE-VILA TUPI- MSE:42204
iniciando: PRAIA GRANDE - OCIAN
Treinando modelo: PRAIA GRANDE-OCIAN
Modelo Treinado: PRAIA GRANDE-OCIAN- MSE:45962
iniciando: PRAIA GRANDE - VILA MIRIM
Treinando modelo: PRAIA GRANDE-VILA MIRIM
Modelo Treinado: PRAIA GRANDE-VILA MIRIM- MSE:60889
iniciando: PRAIA GRANDE - MARACANÃ
Treinando modelo: PRAIA GRANDE-MARACANÃ
Modelo Treinado: PRAIA GRANDE-MARACANÃ- MSE:69779
iniciando: PRAIA GRANDE - VILA CAIÇARA
Treinando modelo: PRAIA GRANDE-VILA CAIÇARA
Modelo Treinado: PRAIA GRANDE-VILA CAIÇARA- MSE:67379
iniciando: PRAIA GRANDE - REAL
Treinando modelo: PRAIA GRANDE-REAL
Modelo Treinado: PRAIA GRANDE-REAL- MSE:40096
iniciando: PRAIA GRANDE - BALNEÁRIO FLÓRIDA
Treinando modelo: PRAIA GRANDE-BALNEÁRIO FLÓRIDA
Modelo Treinado: PRAIA GRANDE-BALNEÁRIO FLÓRIDA- MSE:18106
iniciando: PRAIA GRANDE - JARDIM SOLEMAR
Treinando modelo: PRAIA GRANDE-JARDIM SOLEMAR
Modelo Treinado: PRAIA GRANDE-JARDIM SOLEMAR- MSE:44713
iniciando: SANTOS - PONTA DA PRAIA
Treinando modelo: SANTOS-PONTA DA PRAIA
Modelo Treinado: SANTOS-PONTA DA PRAIA- MSE:21064
iniciando: SANTOS - APARECIDA
Treinando modelo: SANTOS-APARECIDA
Modelo Treinado: SANTOS-APARECIDA- MSE:19679
iniciando: SANTOS - EMBARÉ
Treinando modelo: SANTOS-EMBARÉ
Modelo Treinado: SANTOS-EMBARÉ- MSE:18405
iniciando: SANTOS - BOQUEIRÃO
Treinando modelo: SANTOS-BOQUEIRÃO
Modelo Treinado: SANTOS-BOQUEIRÃO- MSE:18795
iniciando: SANTOS - GONZAGA
Treinando modelo: SANTOS-GONZAGA
Modelo Treinado: SANTOS-GONZAGA- MSE:18143
iniciando: SANTOS - JOSÉ MENINO (R. OLAVO BILAC)
Treinando modelo: SANTOS-JOSÉ MENINO (R. OLAVO BILAC)
Modelo Treinado: SANTOS-JOSÉ MENINO (R. OLAVO BILAC)- MSE:21967
iniciando: SANTOS - JOSÉ MENINO (R. FREDERICO OZANAN)
Treinando modelo: SANTOS-JOSÉ MENINO (R. FREDERICO OZANAN)
Modelo Treinado: SANTOS-JOSÉ MENINO (R. FREDERICO OZANAN)- MSE:23092
iniciando: SÃO SEBASTIÃO - PRAINHA
Treinando modelo: SÃO SEBASTIÃO-PRAINHA
Modelo Treinado: SÃO SEBASTIÃO-PRAINHA- MSE:25325
iniciando: SÃO SEBASTIÃO - CIGARRAS
Treinando modelo: SÃO SEBASTIÃO-CIGARRAS
Modelo Treinado: SÃO SEBASTIÃO-CIGARRAS- MSE:9778
iniciando: SÃO SEBASTIÃO - SÃO FRANCISCO
Treinando modelo: SÃO SEBASTIÃO-SÃO FRANCISCO
Modelo Treinado: SÃO SEBASTIÃO-SÃO FRANCISCO- MSE:17901
iniciando: SÃO SEBASTIÃO - ARRASTÃO
Treinando modelo: SÃO SEBASTIÃO-ARRASTÃO
Modelo Treinado: SÃO SEBASTIÃO-ARRASTÃO- MSE:9422
iniciando: SÃO SEBASTIÃO - PONTAL DA CRUZ
Treinando modelo: SÃO SEBASTIÃO-PONTAL DA CRUZ
Modelo Treinado: SÃO SEBASTIÃO-PONTAL DA CRUZ- MSE:19244
iniciando: SÃO SEBASTIÃO - DESERTA
Treinando modelo: SÃO SEBASTIÃO-DESERTA
Modelo Treinado: SÃO SEBASTIÃO-DESERTA- MSE:19110
iniciando: SÃO SEBASTIÃO - PORTO GRANDE
Treinando modelo: SÃO SEBASTIÃO-PORTO GRANDE
Modelo Treinado: SÃO SEBASTIÃO-PORTO GRANDE- MSE:19578
iniciando: SÃO SEBASTIÃO - PRETA DO NORTE
Treinando modelo: SÃO SEBASTIÃO-PRETA DO NORTE
Modelo Treinado: SÃO SEBASTIÃO-PRETA DO NORTE- MSE:20563
iniciando: SÃO SEBASTIÃO - GRANDE
Treinando modelo: SÃO SEBASTIÃO-GRANDE
Modelo Treinado: SÃO SEBASTIÃO-GRANDE- MSE:3641
iniciando: SÃO SEBASTIÃO - BAREQUEÇABA
Treinando modelo: SÃO SEBASTIÃO-BAREQUEÇABA
Modelo Treinado: SÃO SEBASTIÃO-BAREQUEÇABA- MSE:6940
iniciando: SÃO SEBASTIÃO - GUAECÁ
Treinando modelo: SÃO SEBASTIÃO-GUAECÁ
Modelo Treinado: SÃO SEBASTIÃO-GUAECÁ- MSE:2853
iniciando: SÃO SEBASTIÃO - TOQUE-TOQUE GRANDE
Treinando modelo: SÃO SEBASTIÃO-TOQUE-TOQUE GRANDE
Modelo Treinado: SÃO SEBASTIÃO-TOQUE-TOQUE GRANDE- MSE:3084
iniciando: SÃO SEBASTIÃO - TOQUE-TOQUE PEQUENO
Treinando modelo: SÃO SEBASTIÃO-TOQUE-TOQUE PEQUENO
Modelo Treinado: SÃO SEBASTIÃO-TOQUE-TOQUE PEQUENO- MSE:2580
iniciando: SÃO SEBASTIÃO - SANTIAGO
Treinando modelo: SÃO SEBASTIÃO-SANTIAGO
Modelo Treinado: SÃO SEBASTIÃO-SANTIAGO- MSE:3602
iniciando: SÃO SEBASTIÃO - PAÚBA
Treinando modelo: SÃO SEBASTIÃO-PAÚBA
Modelo Treinado: SÃO SEBASTIÃO-PAÚBA- MSE:3870
iniciando: SÃO SEBASTIÃO - MARESIAS
Treinando modelo: SÃO SEBASTIÃO-MARESIAS
Modelo Treinado: SÃO SEBASTIÃO-MARESIAS- MSE:302
iniciando: SÃO SEBASTIÃO - BOIÇUCANGA
Treinando modelo: SÃO SEBASTIÃO-BOIÇUCANGA
Modelo Treinado: SÃO SEBASTIÃO-BOIÇUCANGA- MSE:7856
iniciando: SÃO SEBASTIÃO - CAMBURIZINHO
Treinando modelo: SÃO SEBASTIÃO-CAMBURIZINHO
Modelo Treinado: SÃO SEBASTIÃO-CAMBURIZINHO- MSE:2768
iniciando: SÃO SEBASTIÃO - CAMBURI
Treinando modelo: SÃO SEBASTIÃO-CAMBURI

Modelo Treinado: SÃO SEBASTIÃO-CAMBURI- MSE:9413
iniciando: SÃO SEBASTIÃO - BALEIA
Treinando modelo: SÃO SEBASTIÃO-BALEIA
Modelo Treinado: SÃO SEBASTIÃO-BALEIA- MSE:2904
iniciando: SÃO SEBASTIÃO - SAÍ
Treinando modelo: SÃO SEBASTIÃO-SAÍ
Modelo Treinado: SÃO SEBASTIÃO-SAÍ- MSE:13640
iniciando: SÃO SEBASTIÃO - PRETA
Treinando modelo: SÃO SEBASTIÃO-PRETA
Modelo Treinado: SÃO SEBASTIÃO-PRETA- MSE:8482
iniciando: SÃO SEBASTIÃO - JUQUEÍ (TRAV. SIMÃO FAUSTINO)
Treinando modelo: SÃO SEBASTIÃO-JUQUEÍ (TRAV. SIMÃO FAUSTINO)
Modelo Treinado: SÃO SEBASTIÃO-JUQUEÍ (TRAV. SIMÃO FAUSTINO)- MSE:5218
iniciando: SÃO SEBASTIÃO - JUQUEÍ (R. CRISTIANA)
Treinando modelo: SÃO SEBASTIÃO-JUQUEÍ (R. CRISTIANA)
Modelo Treinado: SÃO SEBASTIÃO-JUQUEÍ (R. CRISTIANA)- MSE:10315
iniciando: SÃO SEBASTIÃO - UNA
Treinando modelo: SÃO SEBASTIÃO-UNA
Modelo Treinado: SÃO SEBASTIÃO-UNA- MSE:5239
iniciando: SÃO SEBASTIÃO - ENGENHO
Treinando modelo: SÃO SEBASTIÃO-ENGENHO
Modelo Treinado: SÃO SEBASTIÃO-ENGENHO- MSE:4598
iniciando: SÃO SEBASTIÃO - JURÉIA DO NORTE
Treinando modelo: SÃO SEBASTIÃO-JURÉIA DO NORTE
Modelo Treinado: SÃO SEBASTIÃO-JURÉIA DO NORTE- MSE:2439
iniciando: SÃO SEBASTIÃO - BORACÉIA - NORTE
Treinando modelo: SÃO SEBASTIÃO-BORACÉIA - NORTE
Modelo Treinado: SÃO SEBASTIÃO-BORACÉIA - NORTE- MSE:3178
iniciando: SÃO SEBASTIÃO - BORACÉIA - R. CUBATÃO
Treinando modelo: SÃO SEBASTIÃO-BORACÉIA - R. CUBATÃO
Modelo Treinado: SÃO SEBASTIÃO-BORACÉIA - R. CUBATÃO- MSE:8503
iniciando: SÃO VICENTE - PRAIA DA DIVISA
Treinando modelo: SÃO VICENTE-PRAIA DA DIVISA
Modelo Treinado: SÃO VICENTE-PRAIA DA DIVISA- MSE:22038
iniciando: SÃO VICENTE - ITARARÉ (POSTO 2)
Treinando modelo: SÃO VICENTE-ITARARÉ (POSTO 2)
Modelo Treinado: SÃO VICENTE-ITARARÉ (POSTO 2)- MSE:14374
iniciando: SÃO VICENTE - PRAIA DA ILHA PORCHAT
Treinando modelo: SÃO VICENTE-PRAIA DA ILHA PORCHAT
Modelo Treinado: SÃO VICENTE-PRAIA DA ILHA PORCHAT- MSE:10972
iniciando: SÃO VICENTE - MILIONÁRIOS
Treinando modelo: SÃO VICENTE-MILIONÁRIOS
Modelo Treinado: SÃO VICENTE-MILIONÁRIOS- MSE:302439
iniciando: SÃO VICENTE - GONZAGUINHA
Treinando modelo: SÃO VICENTE-GONZAGUINHA
Modelo Treinado: SÃO VICENTE-GONZAGUINHA- MSE:243884
iniciando: SÃO VICENTE - PRAINHA (AV. SANTINO BRITO)
Treinando modelo: SÃO VICENTE-PRAINHA (AV. SANTINO BRITO)
Modelo Treinado: SÃO VICENTE-PRAINHA (AV. SANTINO BRITO)- MSE:305498
iniciando: UBATUBA - PICINGUABA
Treinando modelo: UBATUBA-PICINGUABA
Modelo Treinado: UBATUBA-PICINGUABA- MSE:9874
iniciando: UBATUBA - FÉLIX
Treinando modelo: UBATUBA-FÉLIX
Modelo Treinado: UBATUBA-FÉLIX- MSE:1981
iniciando: UBATUBA - ITAMAMBUCA
Treinando modelo: UBATUBA-ITAMAMBUCA
Modelo Treinado: UBATUBA-ITAMAMBUCA- MSE:590
iniciando: UBATUBA - RIO  ITAMAMBUCA
Treinando modelo: UBATUBA-RIO  ITAMAMBUCA
Modelo Treinado: UBATUBA-RIO  ITAMAMBUCA- MSE:14104
iniciando: UBATUBA - VERMELHA DO NORTE
Treinando modelo: UBATUBA-VERMELHA DO NORTE
Modelo Treinado: UBATUBA-VERMELHA DO NORTE- MSE:333
iniciando: UBATUBA - PEREQUÊ-AÇU
Treinando modelo: UBATUBA-PEREQUÊ-AÇU
Modelo Treinado: UBATUBA-PEREQUÊ-AÇU- MSE:2652
iniciando: UBATUBA - IPEROIG
Treinando modelo: UBATUBA-IPEROIG
Modelo Treinado: UBATUBA-IPEROIG- MSE:9204
iniciando: UBATUBA - ITAGUÁ (No 230 DA AV. LEOVEGILDO)
Treinando modelo: UBATUBA-ITAGUÁ (No 230 DA AV. LEOVEGILDO)
Modelo Treinado: UBATUBA-ITAGUÁ (No 230 DA AV. LEOVEGILDO)- MSE:24787
iniciando: UBATUBA - ITAGUA (No1724 DA AV. LEOVEGILDO)
Treinando modelo: UBATUBA-ITAGUA (No1724 DA AV. LEOVEGILDO)
Modelo Treinado: UBATUBA-ITAGUA (No1724 DA AV. LEOVEGILDO)- MSE:72706
iniciando: UBATUBA - TENÓRIO
Treinando modelo: UBATUBA-TENÓRIO
Modelo Treinado: UBATUBA-TENÓRIO- MSE:752
iniciando: UBATUBA - VERMELHA
Treinando modelo: UBATUBA-VERMELHA
Modelo Treinado: UBATUBA-VERMELHA- MSE:4
iniciando: UBATUBA - GRANDE
Treinando modelo: UBATUBA-GRANDE
Modelo Treinado: UBATUBA-GRANDE- MSE:361
iniciando: UBATUBA - TONINHAS
Treinando modelo: UBATUBA-TONINHAS
Modelo Treinado: UBATUBA-TONINHAS- MSE:983
iniciando: UBATUBA - ENSEADA
Treinando modelo: UBATUBA-ENSEADA
Modelo Treinado: UBATUBA-ENSEADA- MSE:5968
iniciando: UBATUBA - SANTA RITA
Treinando modelo: UBATUBA-SANTA RITA
Modelo Treinado: UBATUBA-SANTA RITA- MSE:15696
iniciando: UBATUBA - PEREQUÊ-MIRIM
Treinando modelo: UBATUBA-PEREQUÊ-MIRIM
Modelo Treinado: UBATUBA-PEREQUÊ-MIRIM- MSE:17608
iniciando: UBATUBA - SUNUNGA
Treinando modelo: UBATUBA-SUNUNGA
Modelo Treinado: UBATUBA-SUNUNGA- MSE:7703
iniciando: UBATUBA - LÁZARO
Treinando modelo: UBATUBA-LÁZARO
Modelo Treinado: UBATUBA-LÁZARO- MSE:14293
iniciando: UBATUBA - DOMINGAS DIAS
Treinando modelo: UBATUBA-DOMINGAS DIAS
Modelo Treinado: UBATUBA-DOMINGAS DIAS- MSE:1310
iniciando: UBATUBA - DURA
Treinando modelo: UBATUBA-DURA
Modelo Treinado: UBATUBA-DURA- MSE:5721
iniciando: UBATUBA - LAGOINHA (R. ENGENHO VELHO)
Treinando modelo: UBATUBA-LAGOINHA (R. ENGENHO VELHO)
Modelo Treinado: UBATUBA-LAGOINHA (R. ENGENHO VELHO)- MSE:3038
iniciando: UBATUBA - LAGOINHA (CAMPING)
Treinando modelo: UBATUBA-LAGOINHA (CAMPING)
Modelo Treinado: UBATUBA-LAGOINHA (CAMPING)- MSE:1777
iniciando: UBATUBA - SAPÉ
Treinando modelo: UBATUBA-SAPÉ
Modelo Treinado: UBATUBA-SAPÉ- MSE:2987
iniciando: UBATUBA - MARANDUBA
Treinando modelo: UBATUBA-MARANDUBA
Modelo Treinado: UBATUBA-MARANDUBA- MSE:3857